<?php
/***************************************************************************
 *						Theme Modules
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 * 
 *  					Copyright (C) Themify
 * 						http://themify.me
 *
 *  To add custom modules to the theme, create a new 'custom-modules.php' file in the theme folder.
 *  They will be added to the theme automatically.
 * 
 ***************************************************************************/

/**
 * Default Index Layout Module
 * @param array $data Theme settings data
 * @return string Markup for module.
 * @since 1.0.0
 */
function themify_default_layout( $data = array() ){
	$data = themify_get_data();
	/**
	 * Theme Settings Option Key Prefix
	 * @var string
	 */
	$prefix = 'setting-default_';
	
	if ( ! isset( $data[$prefix.'more_text'] ) || '' == $data[$prefix.'more_text'] ) {
		$more_text = __('More', 'themify');
	} else {
		$more_text = $data[$prefix.'more_text'];
	}
	/**
	 * Tertiary options <blank>|yes|no
	 * @var array
	 */
	$default_options = array(
		array('name' => '', 'value' => ''),
		array('name' => __('Yes', 'themify'), 'value' => 'yes'),
		array('name' => __('No', 'themify'), 'value' => 'no')
	);
	/**
	 * Post content display options
	 * @var array
	 */
	$default_display_options = array(
		array('name' => __('Full Content', 'themify'),'value' => 'content'),
		array('name' => __('Excerpt', 'themify'),'value' => 'excerpt'),
		array('name' => __('None', 'themify'),'value' => 'none')
	);
	/**
	 * Post layout options
	 * @var array
	 */
	$default_post_layout_options = array(
		array('value' => 'list-post', 'img' => 'images/layout-icons/list-post.png', 'title' => __('List Post', 'themify'), "selected" => true),
		array('value' => 'grid4', 'img' => 'images/layout-icons/grid4.png', 'title' => __('Grid 4', 'themify')),
		array('value' => 'grid3', 'img' => 'images/layout-icons/grid3.png', 'title' => __('Grid 3', 'themify')),
		array('value' => 'grid2', 'img' => 'images/layout-icons/grid2.png', 'title' => __('Grid 2', 'themify')),
	);
	/**
	 * Sidebar placement options
	 * @var array
	 */
	$sidebar_location_options = array(
		array('value' => 'sidebar1', 'img' => 'images/layout-icons/sidebar1.png', 'selected' => true, 'title' => __('Sidebar Right', 'themify')),
		array('value' => 'sidebar1 sidebar-left', 'img' => 'images/layout-icons/sidebar1-left.png', 'title' => __('Sidebar Left', 'themify')),
		array('value' => 'sidebar-none', 'img' => 'images/layout-icons/sidebar-none.png', 'title' => __('No Sidebar', 'themify'))
	);
	/**
	 * Image alignment options
	 * @var array
	 */
	$alignment_options = array(
		array('name' => '', 'value' => ''),
		array('name' => __('Left', 'themify'), 'value' => 'left'),
		array('name' => __('Right', 'themify'), 'value' => 'right')
	);

	/**
	 * HTML for settings panel
	 * @var string
	 */
	$output = '<div class="themify-info-link">' . __( 'Here you can set the <a href="http://themify.me/docs/default-layouts">Default Layouts</a> for WordPress archive post layout (category, search, archive, tag pages, etc.), single post layout (single post page), and the static Page layout. The default single post and page layout can be override individually on the post/page > edit > Themify Custom Panel.', 'themify' ) . '</div>';
	
	/**
	 * Index Sidebar Option
	 */
	$output .= '<p>
					<span class="label">' . __('Index Sidebar Option', 'themify') . '</span>';
	$val = isset( $data[$prefix.'layout'] ) ? $data[$prefix.'layout'] : '';
	foreach ( $sidebar_location_options as $option ) {
		if ( ( '' == $val || ! $val || ! isset( $val ) ) && ( isset( $option['selected'] ) && $option['selected'] ) ) { 
			$val = $option['value'];
		}
		if ( $val == $option['value'] ) { 
			$class = 'selected';
		} else {
			$class = '';
		}
		$output .= '<a href="#" class="preview-icon '.$class.'" title="'.$option['title'].'"><img src="'.THEME_URI.'/'.$option['img'].'" alt="'.$option['value'].'"  /></a>';	
	}
	
	$output .= '	<input type="hidden" name="'.$prefix.'layout" class="val" value="'.$val.'" />
				</p>';
	/**
	 * Post Layout
	 */
	$output .= '<p>
					<span class="label">' . __('Post Layout', 'themify') . '</span>';
	$val = isset( $data[$prefix.'post_layout'] ) ? $data[$prefix.'post_layout'] : '';	
	foreach ( $default_post_layout_options as $option ) {
		if ( ( '' == $val || ! $val || ! isset( $val ) ) && ( isset( $option['selected'] ) && $option['selected'] ) ) { 
			$val = $option['value'];
		}
		if ( $val == $option['value'] ) { 
			$class = 'selected';
		} else {
			$class = '';
		}
		$output .= '<a href="#" class="preview-icon '.$class.'" title="'.$option['title'].'"><img src="'.THEME_URI.'/'.$option['img'].'" alt="'.$option['value'].'"  /></a>';	
	}
	
	$output .= '	<input type="hidden" name="'.$prefix.'post_layout" class="val" value="'.$val.'" />
				</p>';

	/**
	 * Display Content
	 */
	$output .= '<p>
					<span class="label">' . __('Display Content', 'themify') . '</span> 
					<select name="'.$prefix.'layout_display">'.
						themify_options_module($default_display_options, $prefix.'layout_display').'
					</select>
				</p>';
	
	/**
	 * More Text
	 */
	$output .= '<p>
					<span class="label">' . __('More Text', 'themify') . '</span>
					<input type="text" name="'.$prefix.'more_text" value="'.$more_text.'">
					
					<span class="pushlabel vertical-grouped"><label for="setting-excerpt_more"><input type="checkbox" value="1" id="setting-excerpt_more" name="setting-excerpt_more" '.checked( themify_get( 'setting-excerpt_more' ), 1, false ).'/> ' . __('Display more link button in excerpt mode as well.', 'themify') . '</label></span>
				</p>';

	/**
	 * Order & OrderBy Options
	 */
	$output .= themify_post_sorting_options('setting-index_order', $data);
				
	/**
	 * Hide Post Title
	 */
	$output .= '<p>
					<span class="label">' . __('Hide Post Title', 'themify') . '</span>
					<select name="'.$prefix.'post_title">' .
						themify_options_module($default_options, $prefix.'post_title') . '
					</select>
				</p>';
	
	/**
	 * Unlink Post Title
	 */
	$output .= '<p>
					<span class="label">' . __('Unlink Post Title', 'themify') . '</span>
					<select name="'.$prefix.'unlink_post_title">' .
						themify_options_module($default_options, $prefix.'unlink_post_title') . '
					</select>
				</p>';
	
	/**
	 * Hide Post Meta
	 */
	$output .= themify_post_meta_options($prefix.'post_meta', $data);
	
	/**
	 * Hide Post Date
	 */
	$output .= '<p>
					<span class="label">' . __('Hide Post Date', 'themify') . '</span>
					<select name="'.$prefix.'post_date">' .
						themify_options_module($default_options, $prefix.'post_date') . '
					</select>
				</p>';
	
	/**
	 * Auto Featured Image
	 */
	$output .= '<p>
					<span class="label">' . __('Auto Featured Image', 'themify') . '</span>
					<label for="setting-auto_featured_image"><input type="checkbox" value="1" id="setting-auto_featured_image" name="setting-auto_featured_image" '.checked( themify_get( 'setting-auto_featured_image' ), 1, false ).'/> ' . __('If no featured image is specified, display first image in content.', 'themify') . '</label>
				</p>';
	
	/**
	 * Hide Featured Image
	 */
	$output .= '<p>
					<span class="label">' . __('Hide Featured Image', 'themify') . '</span>
					<select name="'.$prefix.'post_image">' .
						themify_options_module($default_options, $prefix.'post_image') . '
					</select>
				</p>';
	
	/**
	 * Unlink Featured Image
	 */
	$output .= '<p>
					<span class="label">' . __('Unlink Featured Image', 'themify') . '</span>
					<select name="'.$prefix.'unlink_post_image">' .
						themify_options_module($default_options, $prefix.'unlink_post_image') . '
					</select>
				</p>';
	
	/**
	 * Featured Image Sizes
	 */
	$output .= themify_feature_image_sizes_select('image_post_feature_size');
	
	/**
	 * Image Dimensions
	 */	
	$output .= '<p>
					<span class="label">' . __('Image Size', 'themify') . '</span>  
					<input type="text" class="width2" name="setting-image_post_width" value="' . themify_get( 'setting-image_post_width' ) . '" /> ' . __('width', 'themify') . ' <small>(px)</small>  
					<input type="text" class="width2" name="setting-image_post_height" value="' . themify_get( 'setting-image_post_height' ) . '" /> ' . __('height', 'themify') . ' <small>(px)</small>
					<br /><span class="pushlabel"><small>' . __('Enter height = 0 to disable vertical cropping with img.php enabled', 'themify') . '</small></span>
				</p>';
	
	/**
	 * Featured Image Alignment
	 */
	$output .= '<p>
					<span class="label">' . __('Featured Image Alignment', 'themify') . '</span>
					<select name="setting-image_post_align">'.
						themify_options_module($alignment_options, 'setting-image_post_align') . '
					</select>
				</p>';
	
	return $output;
}

/**
 * Markup for fixed header selection module
 * @param array $data
 * @return string
 */
function themify_fixed_header_module( $data = array() ) {

	$data = themify_get_data();

	/**
	 * Variable key in theme settings
	 * @var string
	 */
	$key = 'setting-fixed_header_disabled';

	/**
	 * Module markup
	 * @var string
	 */
	$html = sprintf('<p><label for="%1$s"><input type="checkbox" id="%1$s" name="%1$s" %2$s /> %3$s</label></p>',
		$key,
		checked( themify_get( $key ), 'on', false ),
		__('Check to disable Fixed Header.', 'themify')
	);

	return $html;
}

/**
 * Parallax Scrolling Module
 * @param array $data
 * @return string
 */
function themify_parallax_scrolling_module( $data = array() ) {

	$data = themify_get_data();

	/**
	 * Variable key in theme settings
	 * @var string
	 */
	$key = 'setting-parallax_scrolling_disabled';

	/**
	 * Module markup
	 * @var string
	 */
	$html = sprintf('<p><label for="%1$s"><input type="checkbox" id="%1$s" name="%1$s" %2$s /> %3$s</label></p>',
		$key,
		checked( themify_get( $key ), 'on', false ),
		__('Check to disable Parallax Scrolling.', 'themify')
	);

	return $html;
}

if ( ! function_exists( 'themify_store_info_module' ) ) {
	/**
	 * Homepage Welcome Function
	 * @return string Markup for welcome text control
	 */
	function themify_store_info_module(){
		$data = themify_get_data();
		$key = 'setting-store_info_';

		$zoom_levels = array(
			array('value' => '8', 'name' => __('8 - default', 'themify'), 'selected' => true),
			array('value' => '1', 'name' => '1'),
			array('value' => '2', 'name' => '2'),
			array('value' => '3', 'name' => '3'),
			array('value' => '4', 'name' => '4'),
			array('value' => '5', 'name' => '5'),
			array('value' => '6', 'name' => '6'),
			array('value' => '7', 'name' => '7'),
			array('value' => '8', 'name' => '8'),
			array('value' => '9', 'name' => '9'),
			array('value' => '10', 'name' => '10'),
			array('value' => '11', 'name' => '11'),
			array('value' => '12', 'name' => '12'),
			array('value' => '13', 'name' => '13'),
			array('value' => '14', 'name' => '14'),
			array('value' => '15', 'name' => '15'),
			array('value' => '16', 'name' => '16')
		);

		$out = '<p>
					<span class="label"><label for="'.$key.'address">' . __('Address Info', 'themify') . '</label></span>
					<textarea class="width10" id="'.$key.'address" name="'.$key.'address" rows="4">' . themify_get( $key.'address' ) . '</textarea>
				</p>';

		$out .= '<p>
					<span class="label"><label for="'.$key.'phone">' . __('Phone Number', 'themify') . '</label></span>
					<input type="text" id="'.$key.'phone" name="'.$key.'phone" value="' . themify_get( $key.'phone' ) . '" class="width6" />
				</p>';

		$out .= '<p>
					<span class="label"><label for="'.$key.'hours">' . __('Opening Hours', 'themify') . '</label></span>
					<input type="text" id="'.$key.'hours" name="'.$key.'hours" value="' . themify_get( $key.'hours' ) . '" class="width8" />
				</p>';

		$out .= '<p>
					<span class="label"><label for="'.$key.'map">' . __('Google Map Address', 'themify') . '</label></span>
					<textarea class="width10" id="'.$key.'map" name="'.$key.'map" rows="4">' . themify_get( $key.'map' ) . '</textarea>
					<br/>
					<span class="pushlabel"><small>' . __('This will display as Google Maps in the footer.', 'themify') . '</small></span>
				</p>';

		/**
		 * Display Content
		 */
		$out .= '<p>
					<span class="label">' . __('Map Zoom', 'themify') . '</span>
					<select name="' . $key . 'zoom_level">'.
						themify_options_module( $zoom_levels, $key . 'zoom_level' ) . '
					</select>
				</p>';

		return $out;
	}
}

/**
 * Choose pagination or infinite scroll
 * @param array $data
 * @return string
 */
function themify_pagination_infinite($data=array()){
	$data = themify_get_data();

	$html = '<p>';

	//Infinite Scroll
	$html .= '<input ' . checked( themify_check( 'setting-more_posts' ) ? themify_get( 'setting-more_posts' ) : 'infinite', 'infinite', false ) . ' type="radio" id="setting-more_posts_infinite" name="setting-more_posts" value="infinite" /> ';
	$html .= '<label for="setting-more_posts_infinite">' . __('Infinite Scroll (posts are loaded on the same page)', 'themify') . '</label>';
	$html .= '<br/>';
	$html .= '<label for="setting-autoinfinite"><input class="disable-autoinfinite" type="checkbox" id="setting-autoinfinite" name="setting-autoinfinite" '.checked( themify_get( 'setting-autoinfinite' ), 'on', false ).'/> ' . __('Disable automatic infinite scroll', 'themify').'</label>';
	$html .= '<br/><br/>';

	//Numbered pagination
	$html .= '<input ' . checked( themify_get( 'setting-more_posts' ), 'pagination', false ) . ' type="radio" id="setting-more_posts_pagination" name="setting-more_posts" value="pagination" /> ';
	$html .= '<label for="setting-more_posts_pagination">' . __('Standard Pagination', 'themify') . '</label>';
	$html .= '</p>';

	return $html;
}

if ( ! function_exists( 'themify_transition_effect' ) ) {
	/**
	 * Add transition effect
	 * FlyIn/FadeIn/disabled
	 * @return string
	 */
	function themify_transition_effect() {
		$data = themify_get_data();
		$prefix = 'setting-transition_effect_';
		$fadein_checked = '';
		$mobile_checked = '';
		$disabled_checked = '';

		$mobile_options = array(
			array('name' => __('Off', 'themify'),'value'=>'off'),
			array('name' => __('On', 'themify'),'value'=>'on')
		);

		if ( isset( $data[$prefix.'fadein'] ) && $data[$prefix.'fadein'] ) {
			$fadein_checked = "checked='checked'";	
		}
		if ( isset( $data[$prefix.'mobile_exclude'] ) && $data[$prefix.'mobile_exclude'] ) {
			$mobile_checked = "checked='checked'";
		}
		if ( isset( $data[$prefix.'all_disabled'] ) && $data[$prefix.'all_disabled'] ) {
			$disabled_checked = "checked='checked'";
		}

		$out = '<p>
						<span class="label" style="width:400px;">' . __('Turn off fly-in animation on mobile/tablet for better performance', 'themify') . '</span> 
						<select name="'.$prefix.'mobile_exclude">';
						foreach($mobile_options as $mobile_option){
							$out .= '<option '.selected( themify_get( $prefix.'mobile_exclude' ), $mobile_option['value'], false ).' value="'.$mobile_option['value'].'">'.$mobile_option['name'].'</option>';
						}
		$out .=	'	</select>
					</p>';

		$out .= '<p><label for="'.$prefix.'fadein"><input type="checkbox" id="'.$prefix.'fadein" name="'.$prefix.'fadein" '.$fadein_checked.'/> ' . __('Use fade-in transition effect instead of fly-in', 'themify') . '</label></p>';
		$out .= '<p><label for="'.$prefix.'all_disabled"><input type="checkbox" id="'.$prefix.'all_disabled" name="'.$prefix.'all_disabled" '.$disabled_checked.'/> ' . __('Disable all transition effect', 'themify') . '</label></p>';

		return $out;
	}
}